import { Roboto } from "next/font/google";
import Header from "@/components/layout/Header";
import { AppProvider } from "@/components/AppContext";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400","500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppProvider>
          <main className="max-w-4xl mx-auto p-4">
              <Header />
              {children}
              <footer className='border-t p-8 text-center text-gray-500'>
                &copy; 2024 Food Ordering App. All rights reserved.
              </footer>
          </main>          
        </AppProvider>
      </body>
    </html>
  );
}
